version: "3.9"
services:
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_PASSWORD: password
        networks:
          - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev
    maildev:
        image: maildev/maildev
        container_name: maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev

    api:
        build: api/docker
        container_name: api
        ports:
          - "8082:80"
        volumes:
          - ./api/docker/vhosts:/etc/apache2/sites-available
          - ./api:/var/www
        restart: always
        networks:
            - dev

    ui:
      image: node:lts-alpine
      restart: "no"
      volumes:
        - ./ui:/ui
      working_dir: /ui
      command:
        - sh
        - -c
        - |
            yarn install
            yarn run dev
      ports:
        - 3000:3000

networks:
    dev:

volumes:
    db-data:
