security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 4 # Lowest possible value for bcrypt
            time_cost: 3 # Lowest possible value for argon
            memory_cost: 10 # Lowest possible value for argon

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern: ^/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /token/refresh

        main:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: email
                check_path: /api/login_check
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        login:
            custom_authenticator: App\Security\GoogleAuthenticator
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/api/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/api/cryptos, roles: PUBLIC_ACCESS }
        - { path: ^/api/flux_articles, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/adresses, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/flux_article_users, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/flux_articles, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/user_adresses, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/user_cryptos, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
